version: '3'
services:

 #PHP Service
 app:
   image: appName
   build:
     context: .
     dockerfile: Dockerfile
   container_name: mekalink-app
   restart: unless-stopped
   tty: true
   environment:
     SERVICE_NAME: app
     SERVICE_TAGS: dev
   working_dir: /var/www/
   networks:
     - app-network

 #Nginx Service
 webserver:
   image: nginx:alpine
   container_name: mekalink-webserver
   restart: unless-stopped
   tty: true
   ports:
     - "portApp:80"
     - "443:443"
   volumes:
     - ./:/var/www
     - ./build/nginx/:/etc/nginx/conf.d/
   networks:
     - app-network

 #MySQL Service
 db:
   image: mysql:5.7.22
   container_name: mekalink-db
   restart: unless-stopped
   tty: true
   ports:
     - dbPort:dbPort
   volumes:
     - ./mysql-dockerTag/:/docker-entrypoint-initdb.d
     - ./api:/var/lib/mysql
   environment:
      - MYSQL_ROOT_PASSWORD=dbRootPassword
      - MYSQL_DATABASE=dbDatabase
      - MYSQL_USER=dbUsername
      - MYSQL_PASSWORD=dbPassword
      - MYSQL_HOST_ROOT=%
   networks:
     - app-network

#Docker Networks
networks:
 app-network:
   driver: bridge